INSERT INTO callsign_pool (value) VALUES
('Viper'),('Falcon'),('Blazer'),('Ironhand'),('Longshot'),
('Ghost'),('Reaper'),('Shadow'),('Razor'),('Hammer'),
('Dragon'),('Tiger'),('Red Star'),('Lotus'),('Thunder'),
('Katana'),('Ronin'),('Shogun'),('Raijin'),('Kitsune'),
('Specter'),('Maverick'),('Bandit'),('Storm'),('Hawk'),
('Phoenix'),('Wolf'),('Eagle'),('Cobra'),('Jaguar'),
('Bullseye'),('Crusher'),('Scorpion'),('Knight'),('Sentinel'),
('Nomad'),('Hunter'),('Fang'),('Talon'),('Grizzly'),
('Raptor'),('Sabre'),('Omen'),('Torch'),('Inferno'),
('Blizzard'),('Avalanche'),('Cyclone'),('Typhoon'),('Gale'),
('Comet'),('Meteor'),('Nova'),('Starlord'),('Eclipse'),
('Vanguard'),('Guardian'),('Paladin'),('Warden'),('Crusader'),
('Banshee'),('Wraith'),('Ghoul'),('Phantom'),('Spectral'),
('Valkyrie'),('Berserker'),('Gladius'),('Halberd'),('Lancer'),
('Brick'),('Stonewall'),('Bulldog'),('Bear'),('Moose'),
('Badger'),('Fox'),('Coyote'),('Mustang'),('Stallion'),
('Ranger'),('Pathfinder'),('Seeker'),('Tracker'),('Scout'),
('Dagger'),('Blade'),('Arrow'),('Bolt'),('Slugger'),
('Outlaw'),('Nomad'),('Drifter'),('Rogue'),('Mercury'),
('Saturn'),('Mars'),('Venus'),('Jupiter'),('Neptune'),
('Spartan'),('Trojan'),('Centurion'),('Legion'),('Praetor'),
('Titan'),('Colossus'),('Behemoth'),('Goliath'),('Atlas');

INSERT INTO callsign_pool (value) VALUES
('Anvil'),('Arrowhead'),('Ash'),('Aspen'),('Asp'),
('Barrage'),('Basilisk'),('Blackout'),('Blitz'),('Bolt'),
('Breaker'),('Bronco'),('Buckshot'),('Buzzard'),('Carbine'),
('Carnivore'),('Centaur'),('Charger'),('Chimera'),('Claw'),
('Cobra'),('Colt'),('Condor'),('Coyote'),('Crane'),
('Crossfire'),('Crow'),('Crusader'),('Cyclops'),('Dagger'),
('Dart'),('Defiant'),('Demon'),('Dervish'),('Direwolf'),
('Doomsayer'),('Dragoon'),('Duststorm'),('Eagle Eye'),('Edge'),
('Fencer'),('Feral'),('Firebrand'),('Firestorm'),('Fist'),
('Flash'),('Flint'),('Forge'),('Foxhound'),('Fury'),
('Gargoyle'),('Gauntlet'),('Glacier'),('Gorgon'),('Grim'),
('Grizzly Bear'),('Gunmetal'),('Gunrunner'),('Halberdier'),('Hammerfall'),
('Havoc'),('Hellion'),('Hornet'),('Howler'),('Huntsman'),
('Hydra'),('Iceman'),('Impaler'),('Incubus'),('Infernal'),
('Jackal'),('Javelin'),('Juggernaut'),('Justice'),('Kodiak'),
('Kraken'),('Lancer'),('Leopard'),('Lionheart'),('Lockjaw'),
('Mace'),('Magnetar'),('Manhunter'),('Marksman'),('Mauler'),
('Mongoose'),('Nightshade'),('Obsidian'),('Outrider'),('Overlord'),
('Panther'),('Patriot'),('Pike'),('Pitbull'),('Puma'),
('Quicksilver'),('Rampart'),('Raptor'),('Raven'),('Relentless');

INSERT INTO callsign_pool (value) VALUES
('Clutch'),('Turbo'),('Slick'),('Jester'),('Goose'),
('Maverick Jr'),('Snacktime'),('Hotdog'),('Pogo'),('Bingo'),
('Lucky Shot'),('Banana'),('Pickle'),('Tater'),('Waffles'),
('Cupcake'),('Gravy'),('Meatball'),('Beans'),('Spam'),
('Boomstick'),('Duck'),('Mooseknuckle'),('Sledge'),('Spud'),
('Loaf'),('Dusty'),('Slinky'),('Hiccup'),('Sidecar'),
('Crash'),('Oops'),('Whoops'),('Donut'),('Cookie'),
('Pancake'),('Biscuit'),('Chowder'),('Grunt'),('Lugnut'),
('Clown'),('Dozer'),('Runt'),('Tiny'),('Stretch'),
('Shifty'),('Gremlin'),('Goblin'),('Hobbit'),('Grease'),
('Rusty'),('Gravytrain'),('Jellybean'),('Soggy'),('Butterfingers'),
('Turtle'),('Sloth'),('Zippy'),('Fumbles'),('Bubbles');

INSERT INTO callsign_pool (value) VALUES
('Potato'),('Pickles'),('Taco'),('Nacho'),('Meatloaf'),
('Pudding'),('Cheeseball'),('Popcorn'),('Cabbage'),('Noodles'),
('Muffin'),('Cornbread'),('Ketchup'),('Salsa'),('Hotdogger'),
('Turkey'),('Chickenhawk'),('Liver'),('Tofu'),('Broccoli'),
('Goober'),('Gooseberry'),('Snickers'),('Twinkie'),('Skittles'),
('Milkshake'),('Slappy'),('Whiskers'),('Binky'),('Wiggles'),
('Booger'),('Sneezy'),('Snort'),('Burp'),('Gassy'),
('Dumpster'),('Toaster'),('Microwave'),('Spork'),('Spoon'),
('Clippy'),('Paperclip'),('Rubber Ducky'),('Fuzzy'),('Pajamas'),
('Gremlin King'),('Madcat Lite'),('Tinfoil'),('Pottymouth'),('PogoStick');
