INSERT INTO callsign_pool (value) VALUES
('Viper'),('Falcon'),('Blazer'),('Ironhand'),('Longshot'),
('Ghost'),('Reaper'),('Shadow'),('Razor'),('Hammer'),
('Dragon'),('Tiger'),('Red Star'),('Lotus'),('Thunder'),
('Katana'),('Ronin'),('Shogun'),('Raijin'),('Kitsune'),
('Specter'),('Maverick'),('Bandit'),('Storm'),('Hawk'),
('Phoenix'),('Wolf'),('Eagle'),('Cobra'),('Jaguar'),
('Bullseye'),('Crusher'),('Scorpion'),('Knight'),('Sentinel'),
('Nomad'),('Hunter'),('Fang'),('Talon'),('Grizzly'),
('Raptor'),('Sabre'),('Omen'),('Torch'),('Inferno'),
('Blizzard'),('Avalanche'),('Cyclone'),('Typhoon'),('Gale'),
('Comet'),('Meteor'),('Nova'),('Starlord'),('Eclipse'),
('Vanguard'),('Guardian'),('Paladin'),('Warden'),('Crusader'),
('Banshee'),('Wraith'),('Ghoul'),('Phantom'),('Spectral'),
('Valkyrie'),('Berserker'),('Gladius'),('Halberd'),('Lancer'),
('Brick'),('Stonewall'),('Bulldog'),('Bear'),('Moose'),
('Badger'),('Fox'),('Coyote'),('Mustang'),('Stallion'),
('Ranger'),('Pathfinder'),('Seeker'),('Tracker'),('Scout'),
('Dagger'),('Blade'),('Arrow'),('Bolt'),('Slugger'),
('Outlaw'),('Nomad'),('Drifter'),('Rogue'),('Mercury'),
('Saturn'),('Mars'),('Venus'),('Jupiter'),('Neptune'),
('Spartan'),('Trojan'),('Centurion'),('Legion'),('Praetor'),
('Titan'),('Colossus'),('Behemoth'),('Goliath'),('Atlas');

INSERT INTO callsign_pool (value) VALUES
('Anvil'),('Arrowhead'),('Ash'),('Aspen'),('Asp'),
('Barrage'),('Basilisk'),('Blackout'),('Blitz'),('Bolt'),
('Breaker'),('Bronco'),('Buckshot'),('Buzzard'),('Carbine'),
('Carnivore'),('Centaur'),('Charger'),('Chimera'),('Claw'),
('Cobra'),('Colt'),('Condor'),('Coyote'),('Crane'),
('Crossfire'),('Crow'),('Crusader'),('Cyclops'),('Dagger'),
('Dart'),('Defiant'),('Demon'),('Dervish'),('Direwolf'),
('Doomsayer'),('Dragoon'),('Duststorm'),('Eagle Eye'),('Edge'),
('Fencer'),('Feral'),('Firebrand'),('Firestorm'),('Fist'),
('Flash'),('Flint'),('Forge'),('Foxhound'),('Fury'),
('Gargoyle'),('Gauntlet'),('Glacier'),('Gorgon'),('Grim'),
('Grizzly Bear'),('Gunmetal'),('Gunrunner'),('Halberdier'),('Hammerfall'),
('Havoc'),('Hellion'),('Hornet'),('Howler'),('Huntsman'),
('Hydra'),('Iceman'),('Impaler'),('Incubus'),('Infernal'),
('Jackal'),('Javelin'),('Juggernaut'),('Justice'),('Kodiak'),
('Kraken'),('Lancer'),('Leopard'),('Lionheart'),('Lockjaw'),
('Mace'),('Magnetar'),('Manhunter'),('Marksman'),('Mauler'),
('Mongoose'),('Nightshade'),('Obsidian'),('Outrider'),('Overlord'),
('Panther'),('Patriot'),('Pike'),('Pitbull'),('Puma'),
('Quicksilver'),('Rampart'),('Raptor'),('Raven'),('Relentless');
