-- ===========================
-- Mercenary Name Pool
-- Mixed Inner Sphere nationalities — faction agnostic fallback
-- ===========================

-- Male First Names (150)
INSERT INTO name_pool (faction, name_type, value) VALUES
-- British/Celtic
('Mercenary','first_male','James'),
('Mercenary','first_male','William'),
('Mercenary','first_male','Robert'),
('Mercenary','first_male','Thomas'),
('Mercenary','first_male','Edward'),
('Mercenary','first_male','George'),
('Mercenary','first_male','Richard'),
('Mercenary','first_male','Henry'),
('Mercenary','first_male','Arthur'),
('Mercenary','first_male','Duncan'),
('Mercenary','first_male','Malcolm'),
('Mercenary','first_male','Ewan'),
('Mercenary','first_male','Brendan'),
('Mercenary','first_male','Declan'),
('Mercenary','first_male','Connor'),
('Mercenary','first_male','Patrick'),
-- German
('Mercenary','first_male','Klaus'),
('Mercenary','first_male','Dieter'),
('Mercenary','first_male','Heinrich'),
('Mercenary','first_male','Werner'),
('Mercenary','first_male','Gerhard'),
('Mercenary','first_male','Helmut'),
('Mercenary','first_male','Friedrich'),
('Mercenary','first_male','Karl'),
('Mercenary','first_male','Rudolf'),
('Mercenary','first_male','Gunther'),
('Mercenary','first_male','Wolfgang'),
('Mercenary','first_male','Manfred'),
('Mercenary','first_male','Ernst'),
('Mercenary','first_male','Horst'),
-- French
('Mercenary','first_male','Jean'),
('Mercenary','first_male','Pierre'),
('Mercenary','first_male','Michel'),
('Mercenary','first_male','François'),
('Mercenary','first_male','Claude'),
('Mercenary','first_male','Luc'),
('Mercenary','first_male','René'),
('Mercenary','first_male','Gaston'),
('Mercenary','first_male','Marcel'),
('Mercenary','first_male','Étienne'),
('Mercenary','first_male','Armand'),
('Mercenary','first_male','Théodore'),
-- Japanese/East Asian
('Mercenary','first_male','Kenji'),
('Mercenary','first_male','Hiroshi'),
('Mercenary','first_male','Takeshi'),
('Mercenary','first_male','Ryu'),
('Mercenary','first_male','Daichi'),
('Mercenary','first_male','Makoto'),
('Mercenary','first_male','Isamu'),
('Mercenary','first_male','Jiro'),
('Mercenary','first_male','Wei'),
('Mercenary','first_male','Chen'),
('Mercenary','first_male','Lin'),
('Mercenary','first_male','Rong'),
('Mercenary','first_male','Bao'),
('Mercenary','first_male','Hao'),
-- Russian/Slavic
('Mercenary','first_male','Alexei'),
('Mercenary','first_male','Dmitri'),
('Mercenary','first_male','Nikolai'),
('Mercenary','first_male','Vladimir'),
('Mercenary','first_male','Sergei'),
('Mercenary','first_male','Ivan'),
('Mercenary','first_male','Boris'),
('Mercenary','first_male','Yuri'),
('Mercenary','first_male','Mikhail'),
('Mercenary','first_male','Pavel'),
('Mercenary','first_male','Andrei'),
('Mercenary','first_male','Viktor'),
-- Italian
('Mercenary','first_male','Marco'),
('Mercenary','first_male','Luca'),
('Mercenary','first_male','Antonio'),
('Mercenary','first_male','Giovanni'),
('Mercenary','first_male','Matteo'),
('Mercenary','first_male','Enzo'),
('Mercenary','first_male','Salvatore'),
('Mercenary','first_male','Bruno'),
('Mercenary','first_male','Carlo'),
('Mercenary','first_male','Domenico'),
-- Spanish/Portuguese
('Mercenary','first_male','Carlos'),
('Mercenary','first_male','Miguel'),
('Mercenary','first_male','Diego'),
('Mercenary','first_male','Alejandro'),
('Mercenary','first_male','Rafael'),
('Mercenary','first_male','Fernando'),
('Mercenary','first_male','Pedro'),
('Mercenary','first_male','Jorge'),
('Mercenary','first_male','Rodrigo'),
('Mercenary','first_male','Santiago'),
-- Scandinavian
('Mercenary','first_male','Erik'),
('Mercenary','first_male','Lars'),
('Mercenary','first_male','Bjorn'),
('Mercenary','first_male','Gunnar'),
('Mercenary','first_male','Leif'),
('Mercenary','first_male','Sven'),
('Mercenary','first_male','Ragnar'),
('Mercenary','first_male','Harald'),
('Mercenary','first_male','Olaf'),
('Mercenary','first_male','Axel'),
-- Dutch/Flemish
('Mercenary','first_male','Dirk'),
('Mercenary','first_male','Pieter'),
('Mercenary','first_male','Willem'),
('Mercenary','first_male','Hendrik'),
('Mercenary','first_male','Cornelius'),
('Mercenary','first_male','Ruud'),
-- Arabic/Middle Eastern
('Mercenary','first_male','Hassan'),
('Mercenary','first_male','Karim'),
('Mercenary','first_male','Omar'),
('Mercenary','first_male','Tariq'),
('Mercenary','first_male','Jamal'),
('Mercenary','first_male','Reza'),
('Mercenary','first_male','Amir'),
-- African/Pan-African
('Mercenary','first_male','Kwame'),
('Mercenary','first_male','Kofi'),
('Mercenary','first_male','Emeka'),
('Mercenary','first_male','Chukwu'),
('Mercenary','first_male','Adebayo'),
('Mercenary','first_male','Jabari'),
('Mercenary','first_male','Zuberi'),
-- Native American inspired
('Mercenary','first_male','Dakota'),
('Mercenary','first_male','Cheyenne'),
('Mercenary','first_male','Hawke'),
-- Generic/Mixed
('Mercenary','first_male','Marcus'),
('Mercenary','first_male','Victor'),
('Mercenary','first_male','Rex'),
('Mercenary','first_male','Cole'),
('Mercenary','first_male','Drake'),
('Mercenary','first_male','Grant'),
('Mercenary','first_male','Hunter'),
('Mercenary','first_male','Lance'),
('Mercenary','first_male','Reid'),
('Mercenary','first_male','Stark'),
('Mercenary','first_male','Troy'),
('Mercenary','first_male','Wade'),
('Mercenary','first_male','Zane'),
('Mercenary','first_male','Colt'),
('Mercenary','first_male','Dex'),
('Mercenary','first_male','Flint'),
('Mercenary','first_male','Gale'),
('Mercenary','first_male','Jace'),
('Mercenary','first_male','Kade'),
('Mercenary','first_male','Nash');

-- Female First Names (120)
INSERT INTO name_pool (faction, name_type, value) VALUES
-- British/Celtic
('Mercenary','first_female','Elizabeth'),
('Mercenary','first_female','Catherine'),
('Mercenary','first_female','Margaret'),
('Mercenary','first_female','Victoria'),
('Mercenary','first_female','Eleanor'),
('Mercenary','first_female','Fiona'),
('Mercenary','first_female','Moira'),
('Mercenary','first_female','Bridget'),
('Mercenary','first_female','Siobhan'),
('Mercenary','first_female','Aoife'),
('Mercenary','first_female','Niamh'),
-- German
('Mercenary','first_female','Helga'),
('Mercenary','first_female','Ingrid'),
('Mercenary','first_female','Greta'),
('Mercenary','first_female','Liesel'),
('Mercenary','first_female','Brunhilde'),
('Mercenary','first_female','Frieda'),
('Mercenary','first_female','Ursula'),
('Mercenary','first_female','Marta'),
('Mercenary','first_female','Gerda'),
('Mercenary','first_female','Hilde'),
-- French
('Mercenary','first_female','Marie'),
('Mercenary','first_female','Isabelle'),
('Mercenary','first_female','Camille'),
('Mercenary','first_female','Céline'),
('Mercenary','first_female','Chloé'),
('Mercenary','first_female','Élodie'),
('Mercenary','first_female','Margot'),
('Mercenary','first_female','Sylvie'),
('Mercenary','first_female','Véronique'),
('Mercenary','first_female','Delphine'),
-- Japanese/East Asian
('Mercenary','first_female','Yuki'),
('Mercenary','first_female','Akane'),
('Mercenary','first_female','Keiko'),
('Mercenary','first_female','Naomi'),
('Mercenary','first_female','Sakura'),
('Mercenary','first_female','Rin'),
('Mercenary','first_female','Mei'),
('Mercenary','first_female','Lin'),
('Mercenary','first_female','Xiu'),
('Mercenary','first_female','Jing'),
('Mercenary','first_female','Lan'),
-- Russian/Slavic
('Mercenary','first_female','Natasha'),
('Mercenary','first_female','Irina'),
('Mercenary','first_female','Katya'),
('Mercenary','first_female','Olga'),
('Mercenary','first_female','Sonya'),
('Mercenary','first_female','Vera'),
('Mercenary','first_female','Anya'),
('Mercenary','first_female','Mila'),
('Mercenary','first_female','Zoya'),
('Mercenary','first_female','Tasha'),
-- Italian
('Mercenary','first_female','Sofia'),
('Mercenary','first_female','Giulia'),
('Mercenary','first_female','Francesca'),
('Mercenary','first_female','Elena'),
('Mercenary','first_female','Valentina'),
('Mercenary','first_female','Lucia'),
('Mercenary','first_female','Rosa'),
('Mercenary','first_female','Gianna'),
-- Spanish/Portuguese
('Mercenary','first_female','Isabella'),
('Mercenary','first_female','Carmen'),
('Mercenary','first_female','Lucia'),
('Mercenary','first_female','Gabriela'),
('Mercenary','first_female','Pilar'),
('Mercenary','first_female','Esperanza'),
('Mercenary','first_female','Rosario'),
('Mercenary','first_female','Valentina'),
-- Scandinavian
('Mercenary','first_female','Astrid'),
('Mercenary','first_female','Freya'),
('Mercenary','first_female','Sigrid'),
('Mercenary','first_female','Ingrid'),
('Mercenary','first_female','Solveig'),
('Mercenary','first_female','Ragnhild'),
('Mercenary','first_female','Birgit'),
('Mercenary','first_female','Thyra'),
-- Arabic/Middle Eastern
('Mercenary','first_female','Layla'),
('Mercenary','first_female','Yasmin'),
('Mercenary','first_female','Fatima'),
('Mercenary','first_female','Nadia'),
('Mercenary','first_female','Zara'),
('Mercenary','first_female','Leila'),
('Mercenary','first_female','Aisha'),
-- African/Pan-African
('Mercenary','first_female','Amara'),
('Mercenary','first_female','Zuri'),
('Mercenary','first_female','Adaeze'),
('Mercenary','first_female','Nia'),
('Mercenary','first_female','Yewande'),
('Mercenary','first_female','Imani'),
('Mercenary','first_female','Anika'),
-- Generic/Mixed
('Mercenary','first_female','Alex'),
('Mercenary','first_female','Blake'),
('Mercenary','first_female','Casey'),
('Mercenary','first_female','Dana'),
('Mercenary','first_female','Jordan'),
('Mercenary','first_female','Morgan'),
('Mercenary','first_female','Quinn'),
('Mercenary','first_female','Reese'),
('Mercenary','first_female','Rylan'),
('Mercenary','first_female','Skylar'),
('Mercenary','first_female','Storm'),
('Mercenary','first_female','Raven'),
('Mercenary','first_female','Nova'),
('Mercenary','first_female','Echo'),
('Mercenary','first_female','Vera'),
('Mercenary','first_female','Jade'),
('Mercenary','first_female','Sable'),
('Mercenary','first_female','Vex'),
('Mercenary','first_female','Wraith'),
('Mercenary','first_female','Kira');

-- Last Names (150)
INSERT INTO name_pool (faction, name_type, value) VALUES
-- British/Celtic
('Mercenary','last','Armstrong'),
('Mercenary','last','Blackwood'),
('Mercenary','last','Campbell'),
('Mercenary','last','Crawford'),
('Mercenary','last','Douglas'),
('Mercenary','last','Fletcher'),
('Mercenary','last','Grant'),
('Mercenary','last','Hamilton'),
('Mercenary','last','Hunter'),
('Mercenary','last','MacDonald'),
('Mercenary','last','MacLeod'),
('Mercenary','last','Morrison'),
('Mercenary','last','Murray'),
('Mercenary','last','Reid'),
('Mercenary','last','Ross'),
('Mercenary','last','Stewart'),
('Mercenary','last','Wallace'),
('Mercenary','last','Walsh'),
('Mercenary','last','Brennan'),
('Mercenary','last','Burke'),
('Mercenary','last','Doyle'),
('Mercenary','last','Kelly'),
('Mercenary','last','Murphy'),
('Mercenary','last','Ryan'),
-- German
('Mercenary','last','Bauer'),
('Mercenary','last','Fischer'),
('Mercenary','last','Hoffmann'),
('Mercenary','last','Klein'),
('Mercenary','last','Koch'),
('Mercenary','last','Krause'),
('Mercenary','last','Müller'),
('Mercenary','last','Richter'),
('Mercenary','last','Schmidt'),
('Mercenary','last','Schneider'),
('Mercenary','last','Schroeder'),
('Mercenary','last','Schulz'),
('Mercenary','last','Wagner'),
('Mercenary','last','Weber'),
('Mercenary','last','Wolf'),
('Mercenary','last','Zimmermann'),
('Mercenary','last','Brandt'),
('Mercenary','last','Hartmann'),
('Mercenary','last','Lehmann'),
('Mercenary','last','Neumann'),
-- French
('Mercenary','last','Bernard'),
('Mercenary','last','Blanc'),
('Mercenary','last','Chevalier'),
('Mercenary','last','Dubois'),
('Mercenary','last','Dumont'),
('Mercenary','last','Dupont'),
('Mercenary','last','Fontaine'),
('Mercenary','last','Girard'),
('Mercenary','last','Lefevre'),
('Mercenary','last','Leroy'),
('Mercenary','last','Martin'),
('Mercenary','last','Mercier'),
('Mercenary','last','Morel'),
('Mercenary','last','Moreau'),
('Mercenary','last','Petit'),
('Mercenary','last','Renard'),
('Mercenary','last','Simon'),
('Mercenary','last','Thomas'),
('Mercenary','last','Tremblay'),
('Mercenary','last','Vincent'),
-- Japanese/East Asian
('Mercenary','last','Chen'),
('Mercenary','last','Fujita'),
('Mercenary','last','Goto'),
('Mercenary','last','Hayashi'),
('Mercenary','last','Inoue'),
('Mercenary','last','Ishikawa'),
('Mercenary','last','Kimura'),
('Mercenary','last','Kobayashi'),
('Mercenary','last','Matsuda'),
('Mercenary','last','Nakamura'),
('Mercenary','last','Saito'),
('Mercenary','last','Sato'),
('Mercenary','last','Suzuki'),
('Mercenary','last','Tanaka'),
('Mercenary','last','Wang'),
('Mercenary','last','Wu'),
('Mercenary','last','Yang'),
('Mercenary','last','Zhang'),
-- Russian/Slavic
('Mercenary','last','Ivanov'),
('Mercenary','last','Kozlov'),
('Mercenary','last','Kuznetsov'),
('Mercenary','last','Morozov'),
('Mercenary','last','Novak'),
('Mercenary','last','Petrov'),
('Mercenary','last','Popov'),
('Mercenary','last','Sidorov'),
('Mercenary','last','Smirnov'),
('Mercenary','last','Sokolov'),
('Mercenary','last','Volkov'),
('Mercenary','last','Zhukov'),
('Mercenary','last','Kowalski'),
('Mercenary','last','Wiśniewski'),
-- Italian
('Mercenary','last','Bianchi'),
('Mercenary','last','Bruno'),
('Mercenary','last','Colombo'),
('Mercenary','last','Costa'),
('Mercenary','last','Esposito'),
('Mercenary','last','Ferrari'),
('Mercenary','last','Ferretti'),
('Mercenary','last','Greco'),
('Mercenary','last','Lombardi'),
('Mercenary','last','Mancini'),
('Mercenary','last','Marino'),
('Mercenary','last','Ricci'),
('Mercenary','last','Romano'),
('Mercenary','last','Russo'),
-- Spanish/Portuguese
('Mercenary','last','Alves'),
('Mercenary','last','Ferreira'),
('Mercenary','last','Garcia'),
('Mercenary','last','Gomes'),
('Mercenary','last','Gonzalez'),
('Mercenary','last','Herrera'),
('Mercenary','last','Lopez'),
('Mercenary','last','Martinez'),
('Mercenary','last','Pereira'),
('Mercenary','last','Rodrigues'),
('Mercenary','last','Santos'),
('Mercenary','last','Silva'),
('Mercenary','last','Torres'),
-- Scandinavian
('Mercenary','last','Andersen'),
('Mercenary','last','Berg'),
('Mercenary','last','Dahl'),
('Mercenary','last','Eriksen'),
('Mercenary','last','Hagen'),
('Mercenary','last','Hansen'),
('Mercenary','last','Jensen'),
('Mercenary','last','Karlsson'),
('Mercenary','last','Larsen'),
('Mercenary','last','Lindqvist'),
('Mercenary','last','Nilsson'),
('Mercenary','last','Pedersen'),
('Mercenary','last','Svensson'),
-- Arabic/African/Other
('Mercenary','last','Hassan'),
('Mercenary','last','Ibrahim'),
('Mercenary','last','Khalil'),
('Mercenary','last','Nkosi'),
('Mercenary','last','Okafor'),
('Mercenary','last','Osei'),
('Mercenary','last','Patel'),
('Mercenary','last','Sharma'),
('Mercenary','last','Singh'),
('Mercenary','last','Yilmaz'),
-- Mercenary/Callsign-style surnames
('Mercenary','last','Ashford'),
('Mercenary','last','Blackwood'),
('Mercenary','last','Coldwell'),
('Mercenary','last','Crane'),
('Mercenary','last','Cross'),
('Mercenary','last','Drake'),
('Mercenary','last','Dunn'),
('Mercenary','last','Falk'),
('Mercenary','last','Frost'),
('Mercenary','last','Graves'),
('Mercenary','last','Holt'),
('Mercenary','last','Kane'),
('Mercenary','last','Keller'),
('Mercenary','last','Knox'),
('Mercenary','last','Locke'),
('Mercenary','last','Lynch'),
('Mercenary','last','Mason'),
('Mercenary','last','Quinn'),
('Mercenary','last','Raines'),
('Mercenary','last','Reeves'),
('Mercenary','last','Rourke'),
('Mercenary','last','Ryker'),
('Mercenary','last','Saxon'),
('Mercenary','last','Sloane'),
('Mercenary','last','Stone'),
('Mercenary','last','Thorn'),
('Mercenary','last','Vance'),
('Mercenary','last','Voss'),
('Mercenary','last','Wren'),
('Mercenary','last','York');
